export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/index.html.js"), meta: {"t":"Nicolas Blog","i":"home"} }],
  ["/about.html", { loader: () => import(/* webpackChunkName: "about.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/about.html.js"), meta: {"t":"","y":"a"} }],
  ["/posts/ducktales.html", { loader: () => import(/* webpackChunkName: "posts_ducktales.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/ducktales.html.js"), meta: {"d":1568678400000,"l":"September 16, 2019","c":["Review"],"g":["ducktales","woohoo","series","tv","review"],"v":"https://blacknerdproblems.com/wp-content/uploads/2017/12/ducktales-disney-xd-2017.jpeg","e":"\n<p>Era el año 2016 cuando lei por ahi que harian una adaptacion o remake de<br>\n<strong>Ducktales</strong> en Disney XD y dije: \"Pa que van a traer esa wea?\", despues vi que<br>\nsalieron los diseños y dije, \"meh\", empezo a llamarme la antencion cuando supe<br>\nque <a href=\"https://en.wikipedia.org/wiki/David_Tennant\" target=\"_blank\" rel=\"noopener noreferrer\">David Tennant</a> haria la voz de<br>\nScrooge McDuck (tio Rico MacPato por estos lados) y<br>\n<a href=\"https://en.wikipedia.org/wiki/Danny_Pudi\" target=\"_blank\" rel=\"noopener noreferrer\">Danny Pudi</a> apareceria y<br>\n<a href=\"https://en.wikipedia.org/wiki/Catherine_Tate\" target=\"_blank\" rel=\"noopener noreferrer\">Catherine Tate</a> ahi empezo a<br>\nllamar mi atencion de verdad.</p>","r":{"minutes":2,"words":600},"t":"Ducktales 2017","y":"a"} }],
  ["/posts/feminismo%20y%20machismo.html", { loader: () => import(/* webpackChunkName: "posts_feminismo y machismo.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/feminismo y machismo.html.js"), meta: {"d":1567814400000,"l":"September 6, 2019","c":["Blog"],"g":["feminismo","machismo","comentarios","opinion","texto largo"],"v":"https://borderperiodismo.com/wp-content/uploads/2018/04/778e30849cbe73572833a07f2ae09809-1280x640.jpg","e":"\n<p>Por lo visto comenzare un post con algo un poco problematico para mucha gente,<br>\npero pienso que es necesario que alguien (estoy completamente seguro que mucha<br>\nmas gente lo hace) escriba de lo de opina de esto de la misma forma que critica,<br>\nya veran a lo que voy.</p>\n<h2>El Feminismo de mal llamada tercera ola:</h2>","r":{"minutes":5.21,"words":1562},"t":"Sobre Feminismo Machismo Y La Comodidad De Comentar Desde Tu Computador","y":"a"} }],
  ["/posts/hola%20mundo.html", { loader: () => import(/* webpackChunkName: "posts_hola mundo.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/hola mundo.html.js"), meta: {"d":1567623961000,"l":"September 4, 2019","c":["Blog"],"g":["blog","saludos","noticias"],"v":"https://www.rhino.com/sites/rhino.com/files/styles/article_image/public/2017-10/whitesnakes-500.jpg","e":"\n<p>Si, aca estamos nuevamente, otro blog otro que puede que abandone eventualmente,<br>\npero eso.....</p>\n<p>ahora eso si es un poco mas de pega y el contenido es mas estatico y<br>\naparentemente es mas tecnico, creo que mi necesidad de controlar las cosas que<br>\nhago esta haciendo efecto, por lo mismo ahora uso esta tecnologia.</p>","r":{"minutes":0.43,"words":128},"t":"Hola Mundo","y":"a"} }],
  ["/posts/it%20part%202.html", { loader: () => import(/* webpackChunkName: "posts_it part 2.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/it part 2.html.js"), meta: {"d":1567900800000,"l":"September 7, 2019","c":["Review"],"g":["IT","pennywise","movie","pelicula","review"],"v":"https://cdn-3.expansion.mx/c2/90/23d1c0204c9d932e5c97e4e5a176/it-chapter-2.JPG","e":"\n<p>Esta es de las primeras reviews que voy a hacer en este blog, si, tambien tendre<br>\nde estos! asi que acosumbrense (old man yells at cloud). El viernes a la tarde<br>\ndecidimos con un amigo ir a ver el capitulo final de la saga? de peliculas, la<br>\ncual igual, al menos yo esperaba hace un tiempo.</p>","r":{"minutes":1.89,"words":567},"t":"It Chapter Two","y":"a"} }],
  ["/posts/malcolm%20in%20the%20middle.html", { loader: () => import(/* webpackChunkName: "posts_malcolm in the middle.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/malcolm in the middle.html.js"), meta: {"d":1567987200000,"l":"September 8, 2019","c":["Review"],"g":["malcolm in the middle","malcolm","tv series","import"],"v":"https://1.bp.blogspot.com/-Z7gDqyS54gQ/Wq80bpKN_aI/AAAAAAAABnk/Qsv38rJtcjMVXeKnHJ1bUU_cb1T0WJmOwCLcBGAs/s1600/malcolm-middle-810x456.jpeg","e":"\n<div class=\"hint-container note\">\n<p class=\"hint-container-title\">Note</p>\n<p>Este es el primero de una serie de imports de mi proyecto abandonado<br>\nanteriormente sobre reviews de peliculas y series que me gustan.</p>\n</div>\n<p>Hace un tiempo me propuse una mision: Ver series que veia en la tv cuando chico<br>\ny ver que onda como habian cambiado, por el momento ahora estoy viendo Sabrina:<br>\nThe Teenage Witch (si, voy a poner los nombres originales para todas las series)<br>\ny Malcolm in the Middle (en realidad hay varias mas pero dudo que escriba de<br>\ntodas o si quiera las ponga en la lista)</p>","r":{"minutes":2.57,"words":772},"t":"Malcolm In The Middle","y":"a"} }],
  ["/posts/the%20it%20crowd.html", { loader: () => import(/* webpackChunkName: "posts_the it crowd.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/the it crowd.html.js"), meta: {"d":1568073600000,"l":"September 9, 2019","c":["Review"],"g":["import","review","series","tv","the it crowd"],"v":"https://2.bp.blogspot.com/-cC-UC4snbA8/WsvJcj1O2tI/AAAAAAAABoI/vxUra94lQA4M9kgOfmrTV6FZoLsZaLNPwCLcBGAs/s1600/354109.jpg","e":"\n<div class=\"hint-container note\">\n<p class=\"hint-container-title\">Note</p>\n<p>Este es otro post importado de mi antiguo blog</p>\n</div>\n<p>Dejaremos dos cosas en claro antes de hacer el analisis correspondiente a la<br>\nserie, <s>primero si, el nombre de este blog es referencia directa a esta serie;<br>\nsegundo, no, no somos un equipo de personas que escribe aca, asi que el \"crowd\"<br>\nes super contradictorio, pero me gusta como se lee y suena asi que se<br>\nmantendra.</s></p>","r":{"minutes":1.89,"words":566},"t":"The It Crowd","y":"a"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/index.html.js"), meta: {"t":"Posts"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/index.html.js"), meta: {"t":"Category","I":false} }],
  ["/category/review/", { loader: () => import(/* webpackChunkName: "category_review_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/review/index.html.js"), meta: {"t":"Review Category","I":false} }],
  ["/category/blog/", { loader: () => import(/* webpackChunkName: "category_blog_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/blog/index.html.js"), meta: {"t":"Blog Category","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/index.html.js"), meta: {"t":"Tag","I":false} }],
  ["/tag/ducktales/", { loader: () => import(/* webpackChunkName: "tag_ducktales_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/ducktales/index.html.js"), meta: {"t":"Tag: ducktales","I":false} }],
  ["/tag/woohoo/", { loader: () => import(/* webpackChunkName: "tag_woohoo_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/woohoo/index.html.js"), meta: {"t":"Tag: woohoo","I":false} }],
  ["/tag/series/", { loader: () => import(/* webpackChunkName: "tag_series_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/series/index.html.js"), meta: {"t":"Tag: series","I":false} }],
  ["/tag/tv/", { loader: () => import(/* webpackChunkName: "tag_tv_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/tv/index.html.js"), meta: {"t":"Tag: tv","I":false} }],
  ["/tag/review/", { loader: () => import(/* webpackChunkName: "tag_review_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/review/index.html.js"), meta: {"t":"Tag: review","I":false} }],
  ["/tag/feminismo/", { loader: () => import(/* webpackChunkName: "tag_feminismo_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/feminismo/index.html.js"), meta: {"t":"Tag: feminismo","I":false} }],
  ["/tag/machismo/", { loader: () => import(/* webpackChunkName: "tag_machismo_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/machismo/index.html.js"), meta: {"t":"Tag: machismo","I":false} }],
  ["/tag/comentarios/", { loader: () => import(/* webpackChunkName: "tag_comentarios_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/comentarios/index.html.js"), meta: {"t":"Tag: comentarios","I":false} }],
  ["/tag/opinion/", { loader: () => import(/* webpackChunkName: "tag_opinion_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/opinion/index.html.js"), meta: {"t":"Tag: opinion","I":false} }],
  ["/tag/texto-largo/", { loader: () => import(/* webpackChunkName: "tag_texto-largo_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/texto-largo/index.html.js"), meta: {"t":"Tag: texto largo","I":false} }],
  ["/tag/blog/", { loader: () => import(/* webpackChunkName: "tag_blog_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/blog/index.html.js"), meta: {"t":"Tag: blog","I":false} }],
  ["/tag/saludos/", { loader: () => import(/* webpackChunkName: "tag_saludos_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/saludos/index.html.js"), meta: {"t":"Tag: saludos","I":false} }],
  ["/tag/noticias/", { loader: () => import(/* webpackChunkName: "tag_noticias_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/noticias/index.html.js"), meta: {"t":"Tag: noticias","I":false} }],
  ["/tag/it/", { loader: () => import(/* webpackChunkName: "tag_it_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/it/index.html.js"), meta: {"t":"Tag: IT","I":false} }],
  ["/tag/pennywise/", { loader: () => import(/* webpackChunkName: "tag_pennywise_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/pennywise/index.html.js"), meta: {"t":"Tag: pennywise","I":false} }],
  ["/tag/movie/", { loader: () => import(/* webpackChunkName: "tag_movie_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/movie/index.html.js"), meta: {"t":"Tag: movie","I":false} }],
  ["/tag/pelicula/", { loader: () => import(/* webpackChunkName: "tag_pelicula_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/pelicula/index.html.js"), meta: {"t":"Tag: pelicula","I":false} }],
  ["/tag/malcolm-in-the-middle/", { loader: () => import(/* webpackChunkName: "tag_malcolm-in-the-middle_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/malcolm-in-the-middle/index.html.js"), meta: {"t":"Tag: malcolm in the middle","I":false} }],
  ["/tag/malcolm/", { loader: () => import(/* webpackChunkName: "tag_malcolm_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/malcolm/index.html.js"), meta: {"t":"Tag: malcolm","I":false} }],
  ["/tag/tv-series/", { loader: () => import(/* webpackChunkName: "tag_tv-series_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/tv-series/index.html.js"), meta: {"t":"Tag: tv series","I":false} }],
  ["/tag/import/", { loader: () => import(/* webpackChunkName: "tag_import_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/import/index.html.js"), meta: {"t":"Tag: import","I":false} }],
  ["/tag/the-it-crowd/", { loader: () => import(/* webpackChunkName: "tag_the-it-crowd_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/the-it-crowd/index.html.js"), meta: {"t":"Tag: the it crowd","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/article/index.html.js"), meta: {"t":"Articles","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/star/index.html.js"), meta: {"t":"Star","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"t":"Timeline","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
