export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/index.html.js"), meta: {"t":"Blog Home","i":"home"} }],
  ["/intro.html", { loader: () => import(/* webpackChunkName: "intro.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/intro.html.js"), meta: {"v":"/assets/images/cover3.jpg","e":"\n<p>Place your introduction and profile here.</p>\n","r":{"minutes":0.04,"words":13},"t":"Intro Page","i":"circle-info","y":"a"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/demo/index.html.js"), meta: {"c":["Guide"],"r":{"minutes":0.04,"words":12},"t":"Features demo","i":"laptop-code","y":"a"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"c":["Guide"],"g":["disable"],"e":"<p>You can disable some function and layout on the page by setting the Frontmatter of the page.</p>\n","r":{"minutes":0.28,"words":83},"t":"Disabling layout and features","i":"gears","O":4,"y":"a"} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"c":["Guide"],"g":["encryption"],"n":true,"r":{"minutes":0.3,"words":90},"t":"Encryption Article","i":"lock","y":"a"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"c":["Guide"],"g":["Layout"],"e":"<p>The layout contains:</p>\n<ul>\n<li><a href=\"https://theme-hope.vuejs.press/guide/layout/navbar.html\" target=\"_blank\" rel=\"noopener noreferrer\">Navbar</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/guide/layout/sidebar.html\" target=\"_blank\" rel=\"noopener noreferrer\">Sidebar</a></li>\n<li><a href=\"https://theme-hope.vuejs.press/guide/layout/footer.html\" target=\"_blank\" rel=\"noopener noreferrer\">Footer</a></li>\n</ul>","r":{"minutes":0.35,"words":105},"t":"Layout","i":"object-group","O":2,"y":"a"} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"c":["Guide"],"g":["Markdown"],"e":"<p>VuePress basically generate pages from Markdown files. So you can use it to generate documentation or blog sites easily.</p>\n<p>You should create and write Markdown files, so that VuePress can convert them to different pages according to file structure.</p>\n","r":{"minutes":2.63,"words":789},"t":"Markdown Enhance","i":"fab fa-markdown","O":2,"y":"a"} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/demo/page.html.js"), meta: {"a":"Ms.Hope","d":1577836800000,"l":"December 31, 2019","c":["Guide"],"g":["Page config","Guide"],"u":true,"e":"<p>Content before <code>more</code> comment is regarded as page excerpt.</p>\n","r":{"minutes":1.14,"words":341},"t":"Page Config","i":"file","O":3,"y":"a"} }],
  ["/posts/cherry.html", { loader: () => import(/* webpackChunkName: "posts_cherry.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/cherry.html.js"), meta: {"d":1641686400000,"l":"January 8, 2022","c":["Cherry"],"g":["red","small","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Cherry","i":"pen-to-square","y":"a"} }],
  ["/posts/dragonfruit.html", { loader: () => import(/* webpackChunkName: "posts_dragonfruit.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/dragonfruit.html.js"), meta: {"d":1641772800000,"l":"January 9, 2022","c":["Dragon Fruit","Fruit"],"g":["red","big"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.1,"words":29},"t":"Dragon Fruit","i":"pen-to-square","y":"a"} }],
  ["/posts/strawberry.html", { loader: () => import(/* webpackChunkName: "posts_strawberry.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/strawberry.html.js"), meta: {"d":1641859200000,"l":"January 10, 2022","c":["Fruit","Strawberry"],"g":["red","small"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":27},"t":"Strawberry","i":"pen-to-square","y":"a"} }],
  ["/posts/tomato.html", { loader: () => import(/* webpackChunkName: "posts_tomato.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/tomato.html.js"), meta: {"d":1641945600000,"l":"January 11, 2022","c":["Vegetable"],"g":["red","round"],"u":true,"v":"/assets/images/cover2.jpg","e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.11,"words":32},"t":"Tomato","i":"pen-to-square","y":"a"} }],
  ["/posts/apple/1.html", { loader: () => import(/* webpackChunkName: "posts_apple_1.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/apple/1.html.js"), meta: {"d":1640995200000,"l":"December 31, 2021","c":["Apple"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":28},"t":"Apple 1","i":"pen-to-square","y":"a"} }],
  ["/posts/apple/2.html", { loader: () => import(/* webpackChunkName: "posts_apple_2.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/apple/2.html.js"), meta: {"d":1641081600000,"l":"January 1, 2022","c":["Apple"],"g":["red","big","round"],"e":"\n<p>A apple article being stared.</p>\n","r":{"minutes":0.12,"words":36},"t":"Apple 2","i":"pen-to-square","y":"a"} }],
  ["/posts/apple/3.html", { loader: () => import(/* webpackChunkName: "posts_apple_3.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/apple/3.html.js"), meta: {"d":1641168000000,"l":"January 2, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.1,"words":29},"t":"Apple 3","i":"pen-to-square","y":"a"} }],
  ["/posts/apple/4.html", { loader: () => import(/* webpackChunkName: "posts_apple_4.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/apple/4.html.js"), meta: {"d":1641254400000,"l":"January 3, 2022","c":["Apple","Fruit"],"g":["red","big","round"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.1,"words":29},"t":"Apple 4","i":"pen-to-square","y":"a"} }],
  ["/posts/banana/1.html", { loader: () => import(/* webpackChunkName: "posts_banana_1.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/banana/1.html.js"), meta: {"d":1641340800000,"l":"January 4, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.1,"words":29},"t":"Banana 1","i":"pen-to-square","y":"a"} }],
  ["/posts/banana/2.html", { loader: () => import(/* webpackChunkName: "posts_banana_2.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/banana/2.html.js"), meta: {"d":1641427200000,"l":"January 5, 2022","c":["Banana","Fruit"],"g":["yellow","curly","long"],"e":"\n<p>A banana article being stared with number <code>10</code>.</p>\n","r":{"minutes":0.14,"words":41},"t":"Banana 2","i":"pen-to-square","y":"a"} }],
  ["/posts/banana/3.html", { loader: () => import(/* webpackChunkName: "posts_banana_3.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/banana/3.html.js"), meta: {"d":1641513600000,"l":"January 6, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":28},"t":"Banana 3","i":"pen-to-square","y":"a"} }],
  ["/posts/banana/4.html", { loader: () => import(/* webpackChunkName: "posts_banana_4.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/banana/4.html.js"), meta: {"d":1641600000000,"l":"January 7, 2022","c":["Banana"],"g":["yellow","curly","long"],"e":"\n<h2>Heading 2</h2>\n<p>Here is the content.</p>\n<h3>Heading 3</h3>\n<p>Here is the content.</p>\n","r":{"minutes":0.09,"words":28},"t":"Banana 4","i":"pen-to-square","y":"a"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
  ["/posts/", { loader: () => import(/* webpackChunkName: "posts_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/index.html.js"), meta: {"t":"Posts"} }],
  ["/posts/apple/", { loader: () => import(/* webpackChunkName: "posts_apple_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/apple/index.html.js"), meta: {"t":"Apple"} }],
  ["/posts/banana/", { loader: () => import(/* webpackChunkName: "posts_banana_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/posts/banana/index.html.js"), meta: {"t":"Banana"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/index.html.js"), meta: {"t":"Category","I":false} }],
  ["/category/guide/", { loader: () => import(/* webpackChunkName: "category_guide_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/guide/index.html.js"), meta: {"t":"Guide Category","I":false} }],
  ["/category/cherry/", { loader: () => import(/* webpackChunkName: "category_cherry_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/cherry/index.html.js"), meta: {"t":"Cherry Category","I":false} }],
  ["/category/dragon-fruit/", { loader: () => import(/* webpackChunkName: "category_dragon-fruit_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/dragon-fruit/index.html.js"), meta: {"t":"Dragon Fruit Category","I":false} }],
  ["/category/fruit/", { loader: () => import(/* webpackChunkName: "category_fruit_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/fruit/index.html.js"), meta: {"t":"Fruit Category","I":false} }],
  ["/category/strawberry/", { loader: () => import(/* webpackChunkName: "category_strawberry_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/strawberry/index.html.js"), meta: {"t":"Strawberry Category","I":false} }],
  ["/category/vegetable/", { loader: () => import(/* webpackChunkName: "category_vegetable_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/vegetable/index.html.js"), meta: {"t":"Vegetable Category","I":false} }],
  ["/category/apple/", { loader: () => import(/* webpackChunkName: "category_apple_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/apple/index.html.js"), meta: {"t":"Apple Category","I":false} }],
  ["/category/banana/", { loader: () => import(/* webpackChunkName: "category_banana_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/category/banana/index.html.js"), meta: {"t":"Banana Category","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/index.html.js"), meta: {"t":"Tag","I":false} }],
  ["/tag/disable/", { loader: () => import(/* webpackChunkName: "tag_disable_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/disable/index.html.js"), meta: {"t":"Tag: disable","I":false} }],
  ["/tag/encryption/", { loader: () => import(/* webpackChunkName: "tag_encryption_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/encryption/index.html.js"), meta: {"t":"Tag: encryption","I":false} }],
  ["/tag/layout/", { loader: () => import(/* webpackChunkName: "tag_layout_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/layout/index.html.js"), meta: {"t":"Tag: Layout","I":false} }],
  ["/tag/markdown/", { loader: () => import(/* webpackChunkName: "tag_markdown_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/markdown/index.html.js"), meta: {"t":"Tag: Markdown","I":false} }],
  ["/tag/page-config/", { loader: () => import(/* webpackChunkName: "tag_page-config_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/page-config/index.html.js"), meta: {"t":"Tag: Page config","I":false} }],
  ["/tag/guide/", { loader: () => import(/* webpackChunkName: "tag_guide_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/guide/index.html.js"), meta: {"t":"Tag: Guide","I":false} }],
  ["/tag/red/", { loader: () => import(/* webpackChunkName: "tag_red_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/red/index.html.js"), meta: {"t":"Tag: red","I":false} }],
  ["/tag/small/", { loader: () => import(/* webpackChunkName: "tag_small_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/small/index.html.js"), meta: {"t":"Tag: small","I":false} }],
  ["/tag/round/", { loader: () => import(/* webpackChunkName: "tag_round_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/round/index.html.js"), meta: {"t":"Tag: round","I":false} }],
  ["/tag/big/", { loader: () => import(/* webpackChunkName: "tag_big_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/big/index.html.js"), meta: {"t":"Tag: big","I":false} }],
  ["/tag/yellow/", { loader: () => import(/* webpackChunkName: "tag_yellow_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/yellow/index.html.js"), meta: {"t":"Tag: yellow","I":false} }],
  ["/tag/curly/", { loader: () => import(/* webpackChunkName: "tag_curly_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/curly/index.html.js"), meta: {"t":"Tag: curly","I":false} }],
  ["/tag/long/", { loader: () => import(/* webpackChunkName: "tag_long_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/tag/long/index.html.js"), meta: {"t":"Tag: long","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/article/index.html.js"), meta: {"t":"Articles","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/star/index.html.js"), meta: {"t":"Star","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"/home/nicolas/personal/newblog/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"t":"Timeline","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
